### ISSUE TITLE
Present test results as table

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#109]
Hack into `@testset` to retrieve?

**Comment by adrhill** [comment]
Outer testsets only return a parsable structure when they pass, so this requires a new testset type. However, custom testsets don't get printed when called inside of a `DefaultTestset`.

Leaving this open since a custom testset might also be required for #112.

**Comment by adrhill** [comment]
Closing for now as this would require either:
* defining custom testsets (see above for caveats)
* duplicating [correctness.jl](https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterfaceTest/src/tests/correctness.jl) as it currently makes use of `DefaultTestset`s via `@testset`
