### ISSUE TITLE
The big table of overloads

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#115]
This table recaps the features of each extension, with respect to high-level operators.
Each cell can have four values

- ❌: the backend does not support this operator
- ❔: the backend supports this operator but our extension doesn't call it yet / doesn't handle preparation
- ✅: our extension calls the backend operator and handles preparation if possible

| backend              | derivative | gradient | jacobian | hvp | hessian |
| :------------------- | ---------- | -------- | -------- | --- | ------- |
| ChainRulesCore       | ❌          | ❌        | ❌        | ❌   | ❌       |
| Diffractor           | ❌          | ❌        | ❌        | ❌   | ❌       |
| Enzyme (forward)     | ❌          | ✅        | ✅        | ❌   | ❌       |
| Enzyme (reverse)     | ❌          | ✅        | [❔](https://github.com/EnzymeAD/Enzyme.jl/issues/1391)        | ❌   | ❌       |
| FastDifferentiation  | ✅          | ✅        | ✅        | ✅   | ✅       |
| FiniteDiff           | ✅          | ✅        | ✅        | ❌   | ✅       |
| FiniteDifferences    | ❌          | ✅        | ✅        | ❌   | ❌       |
| ForwardDiff          | ✅          | ✅        | ✅        | ❌   | ✅       |
| PolyesterForwardDiff | ❌          | ✅        | ✅        | ❌   | ❌       |
| ReverseDiff          | ✅          | ✅        | ✅        | ❌   | ✅       |
| SparseDiffTools      | ❌          | ❌        | ✅        | ❌   | [❔](https://github.com/gdalle/DifferentiationInterface.jl/issues/63#issuecomment-2034324854)       |
| Symbolics            | ✅          | ✅        | ✅        | ❌   | ✅       |
| Tapir                | ❌          | [❔](https://github.com/withbayes/Tapir.jl/issues/116)        | ❌        | ❌   | ❌       |
| Tracker              | ❌          | ✅        | ❌        | ❌   | ❌       |
| Zygote               | ❌          | ✅        | ❌        | ❌   | ✅       |

**Comment by adrhill** [comment]
The long-term goal should be to replace all ❔ with ✅, right?

**Comment by adrhill** [comment]
It would be nice to have a copy of this in our developer documentation.

**Comment by gdalle** [comment]
I like having this info in one place to help with maintenance. I think the issue makes more sense?

**Comment by wsmoses** [comment]
@gdalle Enzyme does have support for a pure derivative  (presumably scalar?) operator, you just call autodiff with it.

**Comment by gdalle** [comment]
Thanks, this table is more about the shortcuts that each backend defines with other names. I know that with Enzyme most of what I want to do can be achieved with ´autodiff´, and there are probably a few places where performance is suboptimal, but I'll try to fix those
