### ISSUE TITLE
Pullback not working for some cases in FastDifferentiation

### ISSUE THREAD

**Issue by brianguenter** [JuliaDiff/DifferentiationInterface.jl#131]
https://github.com/gdalle/DifferentiationInterface.jl/blob/5775e5c225e00562fa073c5f28f5c79ff1330243/ext/DifferentiationInterfaceFastDifferentiationExt/allocating.jl#L41

I noticed that your comments said this failed for scalar->matrix. Is this still true or is the comment out of date? If it is failing then could you give me a MWE I can use to debug the problem?

**Comment by gdalle** [comment]
See #132

**Comment by gdalle** [comment]
Actually you can disregard the PR @brianguenter, here's a DI-independent MWE:

Setup:

```julia
using FastDifferentiation
import ForwardDiff
using LinearAlgebra

# for scalar -> array functions only

function prepare_pullback(f)
    x_var = only(make_variables(:x))
    y_var = f(x_var)
    x_vec_var = [x_var]
    y_vec_var = vec(y_var)
    vj_vec_var, v_vec_var = jacobian_transpose_v(y_vec_var, x_vec_var)
    vjp_exe = make_function(vj_vec_var, [x_vec_var; v_vec_var]; in_place=false)
    return vjp_exe
end

function value_and_pullback(f, x::Number, dy::AbstractArray, vjp_exe)
    y = f(x)
    v_vec = vcat(x, vec(dy))
    vj_vec = vjp_exe(v_vec)
    return y, only(vj_vec)
end

f(x::Number) = fill(x, 2, 2)
x = 1.0
dy = reshape(1:4, 2, 2)
```

Output:

```julia
julia> f(x), dot(ForwardDiff.derivative(f, x), dy) # expected result
([1.0 1.0; 1.0 1.0], 10.0)

julia> value_and_pullback(f, x, dy, prepare_pullback(f)) # actual result
([1.0 1.0; 1.0 1.0], 4.0)
```

**Comment by brianguenter** [comment]
found the bug. Again it has to do with Jacobians with constant terms. Will probably take a day or two to fix and make a new patch release.

**Comment by gdalle** [comment]
Those damn constant jacobians... thank you for looking !

**Comment by gdalle** [comment]
However note that the problem also appeared with my DI examples, which involved sines and cosines

**Comment by gdalle** [comment]
```julia
julia> f(x::Number) = fill(sin(x), 2, 2)
f (generic function with 1 method)

julia> x = 1.0
1.0

julia> dy = reshape(1:4, 2, 2)
2×2 reshape(::UnitRange{Int64}, 2, 2) with eltype Int64:
 1  3
 2  4

julia> f(x), dot(ForwardDiff.derivative(f, x), dy) # expected result
([0.8414709848078965 0.8414709848078965; 0.8414709848078965 0.8414709848078965], 5.403023058681398)

julia> value_and_pullback(f, x, dy, prepare_pullback(f)) # actual result
([0.8414709848078965 0.8414709848078965; 0.8414709848078965 0.8414709848078965], 51.86902136334142)
```

**Comment by brianguenter** [comment]
This looks like a separate bug. I normally take the weekends off so it will be Monday or Tuesday before I fix these.

**Comment by gdalle** [comment]
By any reasonable open source standards this is super fast fixing! Thanks so much, but don't stress either 😉

**Comment by gdalle** [comment]
Hey @brianguenter, friendliest of pings on this issue ! If there is something I can do to help, let me know

**Comment by brianguenter** [comment]
I've made the fix and it appears to work. I have to rewrite some test programs that were broken by the fix before releasing the patch, otherwise CI will be broken. 

If you want to test it download this branch: https://github.com/brianguenter/FastDifferentiation.jl/tree/brianguenter/issue67

**Comment by gdalle** [comment]
Awesome! I'll take it for a spin tomorrow. I know @Vaibhavdixit02 is excited to play around with FastDifferentiation.jl, and the working pullbacks will in turn enable fast gradients, which are key for optimization

**Comment by gdalle** [comment]
So unfortunately it breaks right from the start:

```julia
julia> using DifferentiationInterface, FastDifferentiation

julia> gradient(sum, AutoFastDifferentiation(), [1.0])
ERROR: ArgumentError: Cannot setindex! to FastDifferentiation.NoOp()(x1) for an AbstractFill with value x1.
Stacktrace:
  [1] setindex!
    @ ~/.julia/packages/FillArrays/3N7FG/src/FillArrays.jl:53 [inlined]
  [2] FastDifferentiation.DerivativeGraph(roots::FillArrays.Fill{FastDifferentiation.Node, 1, Tuple{…}}, index_type::Type)
    @ FastDifferentiation ~/.julia/packages/FastDifferentiation/fzJio/src/DerivativeGraph.jl:172
  [3] DerivativeGraph
    @ ~/.julia/packages/FastDifferentiation/fzJio/src/DerivativeGraph.jl:169 [inlined]
  [4] jacobian_times_v(terms::FillArrays.Fill{…}, partial_variables::Vector{…})
    @ FastDifferentiation ~/.julia/packages/FastDifferentiation/fzJio/src/Jacobian.jl:147
  [5] prepare_pushforward(f::typeof(sum), ::AutoFastDifferentiation, x::Vector{Float64})
    @ DifferentiationInterfaceFastDifferentiationExt ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/ext/DifferentiationInterfaceFastDifferentiationExt/onearg.jl:20
  [6] prepare_pullback_aux(f::Function, backend::AutoFastDifferentiation, x::Vector{…}, ::DifferentiationInterface.PullbackSlow)
    @ DifferentiationInterface ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/src/pullback.jl:74
  [7] prepare_pullback
    @ ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/src/pullback.jl:66 [inlined]
  [8] prepare_gradient(f::Function, backend::AutoFastDifferentiation, x::Vector{Float64})
    @ DifferentiationInterface ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/src/gradient.jl:46
  [9] gradient(f::Function, backend::AutoFastDifferentiation, x::Vector{Float64})
    @ DifferentiationInterface ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/src/gradient.jl:70
 [10] top-level scope
    @ REPL[21]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
(This is reproducible with the released version of DI)

**Comment by brianguenter** [comment]
try it now.

**Comment by gdalle** [comment]
@brianguenter it seems to be working! Thank you so much for the fix :) Final questions:

- I add the pullbacks in PR https://github.com/gdalle/DifferentiationInterface.jl/pull/174 but I didn't find a convenient way to compute a gradient in FastDifferentiation.jl, other than `jacobian_transpose_v` with a cotangent equal to 1. Can you confirm this is the right way?
- Would it be possible to release a new version with the fix, so that I can incorporate it in DI v0.2?

**Comment by brianguenter** [comment]
I will. Still have to fix a few tests that were broken. Probably won't get done till tomorrow or Monday.

**Comment by gdalle** [comment]
no rush :) thank you so much again, I'm very excited to benchmark against a fully-operational FastDifferentiation

**Comment by brianguenter** [comment]
As for the gradient is the problem that the `jacobian` function of an Rⁿ->R¹ function returns a 1xn matrix instead of a vector? I assumed either a 1xn matrix or a vector would do and made it a matrix for logical consistency. But if the numerical/optimization packages in Julia generally assume a vector and this causes type problems I could make a wrapper function `gradient` that does the conversion for you.

**Comment by brianguenter** [comment]
I'll help you with the benchmarks to ensure that FastDifferentiation is being used in the optimal way.

**Comment by gdalle** [comment]
> As for the gradient is the problem that the jacobian function of an Rⁿ->R¹ function returns a 1xn matrix instead of a vector?

No I was just wondering if there is anything baked in. You're right I could probably use `jacobian` instead of `jacobian_transpose_v`, in case one is faster?

> I'll help you with the benchmarks to ensure that FastDifferentiation is being used in the optimal way.

FastDifferentiation is probably the backend that is most optimized already ;) Maybe we could have a quick call next week to discuss my implementation? It seems easier than doing it through GitHub comments.

**Comment by brianguenter** [comment]
I would expect `jacobian` to be slightly faster than `jacobian_transpose_v`.

Happy to do a call. If we do it near the end of next week that will give me time to look over your code in more detail.

**Comment by gdalle** [comment]
Awesome! Just ping me when the new release gets out, I'll add the final version of the FastDifferentiation bindings to DI, and then leave you time to review

**Comment by gdalle** [comment]
I have added the `jacobian`-based gradient in #180, thanks for the tip!

**Comment by brianguenter** [comment]
The new release is on the Julia registry.
________________________________

**Comment by gdalle** [comment]
Awesome, thanks! I'll add it to DifferentiationInterface today. Free to chat whenever you like, with the caveat that my time zone is European
