### ISSUE TITLE
Possible direct users

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#134]
Meta-issue to survey users of DifferentiationInterface and the related discussions.

### Registered

**[ContinuousNormalizingFlows.jl](https://github.com/impICNF/ContinuousNormalizingFlows.jl)**

- https://github.com/impICNF/ContinuousNormalizingFlows.jl/issues/397
- https://github.com/impICNF/ContinuousNormalizingFlows.jl/pull/399

**[CTBase.jl](https://github.com/control-toolbox/CTBase.jl) and [CTFlows.jl](https://github.com/control-toolbox/CTFlows.jl)**

- https://github.com/control-toolbox/CTBase.jl/issues/25
- https://github.com/control-toolbox/CTBase.jl/pull/140
- https://github.com/control-toolbox/CTBase.jl/pull/141

**[Fronts.jl](https://github.com/gerlero/Fronts.jl)**

- https://github.com/gerlero/Fronts.jl/pull/184

**[ImplicitDifferentiation.jl](https://github.com/JuliaDecisionFocusedLearning/ImplicitDifferentiation.jl)**

- https://github.com/JuliaDecisionFocusedLearning/ImplicitDifferentiation.jl/pull/135

**[ItemResponseFunctions.jl](https://github.com/JuliaPsychometrics/ItemResponseFunctions.jl)**

- https://github.com/JuliaPsychometrics/ItemResponseFunctions.jl/pull/14

**[MarginalLogDensities.jl](https://github.com/ElOceanografo/MarginalLogDensities.jl)**

- https://github.com/ElOceanografo/MarginalLogDensities.jl/issues/13
- https://github.com/ElOceanografo/MarginalLogDensities.jl/pull/25

**[OptimizationBase.jl](https://github.com/SciML/OptimizationBase.jl) and [Optimization.jl](https://github.com/SciML/Optimization.jl)**

- https://github.com/gdalle/DifferentiationInterface.jl/issues/89
- https://github.com/SciML/OptimizationBase.jl/pull/31
- https://github.com/SciML/Optimization.jl/issues/744
- https://github.com/SciML/OptimizationBase.jl/issues/62
- https://github.com/SciML/OptimizationBase.jl/pull/54

**[SimpleNonlinearSolve.jl](https://github.com/SciML/SimpleNonlinearSolve.jl)**

- https://github.com/SciML/SimpleNonlinearSolve.jl/pull/148

### Not registered

**[Hyperelastics.jl](https://github.com/TRACER-LULab/Hyperelastics.jl/pulls)**

- https://github.com/TRACER-LULab/Hyperelastics.jl/pull/144

## Future users

**[ADNLPModels.jl](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl)**

- https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/229

**[AutoDiffOperators.jl](https://github.com/oschulz/AutoDiffOperators.jl)**

- https://github.com/oschulz/AutoDiffOperators.jl/issues/17

**[DataDrivenLux.jl](https://github.com/SciML/DataDrivenDiffEq.jl)**

- https://github.com/SciML/DataDrivenDiffEq.jl/issues/519

**[DifferentialEquations.jl](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl)**

- https://github.com/SciML/DifferentialEquations.jl/issues/1027

**[Flux.jl](https://github.com/FluxML/Flux.jl)**

- https://github.com/gdalle/DifferentiationInterface.jl/issues/106
- https://github.com/gdalle/DifferentiationInterface.jl/issues/107

**[Lux.jl](https://github.com/LuxDL/Lux.jl)**

- https://github.com/LuxDL/Lux.jl/issues/544
- https://github.com/LuxDL/Lux.jl/issues/573
- https://github.com/LuxDL/Lux.jl/issues/600

**[MuseInference.jl](https://github.com/marius311/MuseInference.jl)**

- https://github.com/marius311/MuseInference.jl/issues/19

**[NNLib.jl](https://github.com/FluxML/NNlib.jl)**

- https://github.com/gdalle/DifferentiationInterface.jl/issues/105
- https://github.com/FluxML/NNlib.jl/pull/570

**[NonlinearSolve.jl](https://github.com/SciML/NonlinearSolve.jl)**

- https://github.com/SciML/NonlinearSolve.jl/issues/415

**[ProximalAlgorithms.jl](https://github.com/JuliaFirstOrder/ProximalAlgorithms.jl)**

- https://github.com/JuliaFirstOrder/ProximalAlgorithms.jl/pull/93

**[SciMLSensitivity.jl](https://github.com/SciML/SciMLSensitivity.jl)**

- https://github.com/SciML/SciMLSensitivity.jl/issues/1040

**[SNOW.jl](https://github.com/byuflowlab/SNOW.jl)**

- https://github.com/byuflowlab/SNOW.jl/issues/17

**[Turing.jl](https://github.com/TuringLang/Turing.jl) through [LogDensityProblemsAD.jl](https://github.com/tpapp/LogDensityProblemsAD.jl)**

- https://github.com/TuringLang/Turing.jl/issues/2187
- https://github.com/tpapp/LogDensityProblemsAD.jl/issues/26
- https://github.com/tpapp/LogDensityProblemsAD.jl/pull/29

**[VoronoiFVM.jl](https://github.com/j-fu/VoronoiFVM.jl)**

- https://github.com/j-fu/VoronoiFVM.jl/issues/109

**[WaterLily.jl](https://github.com/WaterLily-jl/WaterLily.jl)**

- https://github.com/gdalle/DifferentiationInterface.jl/issues/355

**Comment by prbzrg** [comment]
I like this package 👍 `ContinuousNormalizingFlows` will use it from now on 🚀
https://github.com/impICNF/ContinuousNormalizingFlows.jl/pull/399

**Comment by ElOceanografo** [comment]
Currently working on integrating this into [MarginalLogDensities](https://github.com/ElOceanografo/MarginalLogDensities.jl)...

**Comment by gerlero** [comment]
[Fronts](https://github.com/gerlero/Fronts.jl) is about to switch to `DifferentiationInterface`: https://github.com/gerlero/Fronts.jl/pull/184

**Comment by gdalle** [comment]
Closing because there are starting to be too many to keep track
