### ISSUE TITLE
add jvp and vjp

### ISSUE THREAD

**Issue by rveltz** [JuliaDiff/DifferentiationInterface.jl#155]
Hi,

I am looking forward to this new package!!

May I ask you to add the jvp and vjp functions please as a conveniency?

Thanks a lot

Best regards

**Comment by gdalle** [comment]
Hi Romain!
Not sure what you mean by adding, it's already there as `pushforward` and `pullback`!
Relevant docs: https://gdalle.github.io/DifferentiationInterface.jl/DifferentiationInterface/dev/overview/
Unless you wanted something different?

**Comment by rveltz** [comment]
Oh... excellent!
Thank you
