### ISSUE TITLE
Go back from BangBang convention to enforcing mutation?

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#168]
Just to keep track of the discussion with @devmotion: https://github.com/SciML/OptimizationBase.jl/pull/31#discussion_r1559316902

**Comment by gdalle** [comment]
Main problems spotted:

- even stuff like `ForwardDiff.jacobian!` is not guaranteed to mutate with a `DiffResult` object, see https://github.com/JuliaDiff/DiffResults.jl/issues/27

**Comment by devmotion** [comment]
I assume DiffResults predates the bang bang convention. But similar to the discussion in the other thread IMO this behaviour (note that these examples are for immutable arrays!) is not relevant for the point I'm trying to make: When you require/assume mutable containers, then you should directly use the more direct and more efficient inplace function. Bang bang is useful for generic code that accepts both mutable and immutable  arrays.

**Comment by gdalle** [comment]
The code in DI is trying to be as generic as possible, but I realized yesterday that every downstream user, myself included, would have to make heavy use of copyto!(x, operator!!(x)) which is suboptimal, so I am indeed working to change that
