### ISSUE TITLE
Support Forward Mode of `Zygote`

### ISSUE THREAD

**Issue by prbzrg** [JuliaDiff/DifferentiationInterface.jl#251]
It seems that `Zygote` support forward AD but a few use that. Is there any plan to support it?
I opened this issue to ask for comments.

Related API:
- `Zygote.pushforward`
- `Zygote.forwarddiff`

Related Links:
https://github.com/FluxML/Zygote.jl/tree/master/src/forward

https://github.com/FluxML/Zygote.jl/tree/master/test/forward

https://github.com/FluxML/Zygote.jl/pull/503

https://github.com/FluxML/Zygote.jl/issues/1098

**Comment by adrhill** [comment]
If this forward mode is feature-complete, the first step is to add it to ADTypes. Then DI can support both modes the same way it does with Enzyme.

**Comment by gdalle** [comment]
It's not public and it's [barely used](https://github.com/FluxML/Zygote.jl/issues/1098#issuecomment-2107069659) so we won't touch it
