### ISSUE TITLE
Limit abilities of backend wrappers

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#274]
The gist:

- `SecondOrder` should only be able to call second-order operators (already the case)
- `AutoSparse` should only be able to call `jacobian` and `hessian` (breaking)

Advantages:

- Reduces fallback boilerplate like the hideous https://github.com/gdalle/DifferentiationInterface.jl/blob/main/DifferentiationInterface/src/sparse/fallbacks.jl
- Reduces the risk of error

Drawbacks:

- Users will often have to specify several backends to get things to work. For optimization or nonlinear solve:
  1. The user gives a forward backend and a reverse backend
  2. The package dev takes care of mixing them in the appropriate way for gradients, Jacobianss and Hessians

**Comment by adrhill** [comment]
> `AutoSparse` should only be able to call `jacobian` and `hessian` (breaking)

I think this is the right call. Any other operators besides the Jacobian and Hessian are non-sparse and it would be misleading to call them using `AutoSparse`.
