### ISSUE TITLE
Use `autodiff_deferred` for the inner gradient in Enzyme hessian

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiff/DifferentiationInterface.jl#278]
I think this might reduce the number of failure cases of second-order with Enzyme. Looking at the code this change didn't seem straightforward, hence just opening an issue and not a PR :)

**Comment by gdalle** [comment]
Thanks! Do you have examples of second order Enzyme use? The only one I know is in the JuMP documentation

**Comment by Vaibhavdixit02** [comment]
https://github.com/SciML/OptimizationBase.jl/blob/main/ext/OptimizationEnzymeExt.jl#L38-L145 and https://enzyme.mit.edu/julia/dev/generated/autodiff/#Forward-over-reverse should hopefully help?

**Comment by gdalle** [comment]
Thanks, working on it. I think I'll have to define a custom `hvp` function for Enzyme over Enzyme.
I would love to get your input on https://discourse.julialang.org/t/second-order-autodiff-which-combinations-should-work/114892

**Comment by gdalle** [comment]
Other link for Enzyme: https://jump.dev/JuMP.jl/stable/tutorials/nonlinear/operator_ad/#Hessian-3
