### ISSUE TITLE
docs: backends: broken markdown in table row for Diffractor.jl

### ISSUE THREAD

**Issue by nsajko** [JuliaDiff/DifferentiationInterface.jl#293]
https://gdalle.github.io/DifferentiationInterface.jl/DifferentiationInterface/dev/backends/#List-of-backends

The markdown in the row for Diffractor.jl seems broken, note the first two columns.

**Comment by gdalle** [comment]
Thanks for the catch, that's an easy fix. I have a backend-to-string function that outputs `"Diffractor (forward|reverse)"` and the vertical bar is interpreted by Markdown as a table separator. I'll replace it with an `or`
