### ISSUE TITLE
Return `gradient` with `hessian`, or `derivative` with `second_derivative`

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#299]
As discussed in #296, defining the following operators would allow some backends to optimize the joint computation:

- `value_derivative_and_second_derivative`
- `value_gradient_and_hessian`

Main issue: with what kind of scenario do we test those?

**Comment by adrhill** [comment]
I guess we could reuse our Hessian scenarios and add Gradient information to them?

**Comment by gdalle** [comment]
Yeah we had the same idea, after some thinking I added a `first_order_ref` to the second-order scenarios in #300
