### ISSUE TITLE
Structured arrays

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#35]
MWE by @mcabbott

```julia
julia> backend = ADTypes.AutoForwardDiff();  # from docs example

julia> DifferentiationInterface.value_and_gradient(backend, f, [1., 2., 3.])
(14.0, [2.0, 4.0, 6.0])

julia> DifferentiationInterface.value_and_gradient(backend, f, LinRange(1,3,3))
(14.0, [2.0, 4.0, 6.0])

julia> DifferentiationInterface.value_and_gradient(backend, f, Symmetric(ones(3,3)))
ERROR: ArgumentError: Cannot set a non-diagonal index in a symmetric matrix
```

The issue is that `value_and_gradient` creates a `grad` object with `similar(x)` and then tries to mutate it by calling `value_and_gradient!`. This fails for a `Symmetric` matrix.

**Comment by gdalle** [comment]
The package is gonna be agnostic about tangent / cotangent structure, but we can try to avoid some of these bugs with a more careful fallback structure (like avoiding mutation when we can).

**Comment by gdalle** [comment]
See the recent discussion on Enzyme:
- https://github.com/EnzymeAD/Enzyme.jl/issues/1334

**Comment by gdalle** [comment]
The question of sparse arrays is also relevant

**Comment by adrhill** [comment]
> we can try to avoid some of these bugs with a more careful fallback structure (like avoiding mutation when we can). 

What would these fallbacks dispatch on? It sounds like this would require adding traits for each array type in the Julia ecosystem. 
Or should we change our existing `AbstractArray` type annotations to `Array` and be more conservative / non-mutating with `AbstractArray`?

**Comment by gdalle** [comment]
Yeah this is a limitation of ForwardDiff actually. We don't have any grasp on how the backends handle structure, and we cannot work without at least mutation

**Comment by gdalle** [comment]
Closing it cause there isn't much we can do

**Comment by mcabbott** [comment]
It's possible that ForwardDiff should call 3-arg `similar(x, T, axes(x))` to strip structure. Without thinking too hard about the mathematics, this appears to match Zygote (where we did think hard):
```julia
julia> using ForwardDiff, Zygote

julia> f(x) = sum(abs2, x);

julia> x = Symmetric(rand(Int8, 3, 3) .+ 0.0)
3×3 Symmetric{Float64, Matrix{Float64}}:
 -35.0   -52.0  -62.0
 -52.0  -113.0  -75.0
 -62.0   -75.0   45.0

julia> @eval ForwardDiff function GradientConfig(f::F,
                               x::AbstractArray{V},
                               ::Chunk{N} = Chunk(x),
                               ::T = Tag(f, V)) where {F,V,N,T}
           seeds = construct_seeds(Partials{N,V})
           duals = similar(x, Dual{T,V,N}, axes(x))
           return GradientConfig{T,V,N,typeof(duals)}(seeds, duals)
       end
ForwardDiff.GradientConfig

julia> g1 = ForwardDiff.gradient!(similar(x, axes(x)), f, x)
3×3 Matrix{Float64}:
  -70.0  -104.0  -124.0
 -104.0  -226.0  -150.0
 -124.0  -150.0    90.0

julia> g2 = Zygote.gradient(f, x)[1]
3×3 Symmetric{Float64, Matrix{Float64}}:
  -70.0  -104.0  -124.0
 -104.0  -226.0  -150.0
 -124.0  -150.0    90.0
```
The one above was the first example I tried, as I wondered whether this package was taking charge of allocating such arrays... I think the answer is (1) while it offers `gradient!` and `gradient`, the first does not call the second, and (2) there are two allocations in this anyway, and both need to be changed. This comment:
 
> creates a grad object with `similar(x)` and then tries to mutate it by calling `value_and_gradient!`.

is only about one of the allocations, for the result.

**Comment by mcabbott** [comment]
However, if this issue is about more than ForwardDiff then that isn't the end. The linked Enzyme issue is trickier, as it will sometimes return a struct whose interpretation is quite different:
```julia
julia> using DifferentiationInterface, ADTypes, Enzyme

julia> g3 = DifferentiationInterface.gradient(ADTypes.AutoEnzyme(Enzyme.Reverse), f, x)
3×3 Symmetric{Float64, Matrix{Float64}}:
  -70.0  -208.0  -248.0
 -208.0  -226.0  -300.0
 -248.0  -300.0    90.0

julia> norm(g2)  # from Zygote above
401.82085560607726

julia> norm(g3)  # not really valid!
673.507238268454

julia> DifferentiationInterface.gradient(ADTypes.AutoEnzyme(Enzyme.Reverse), sum, LinRange(1,2,3))
ERROR: MethodError: no method matching Duplicated(::LinRange{Float64, Int64}, ::Vector{Float64})
Stacktrace:
 [1] gradient
   @ ~/.julia/packages/Enzyme/l4FS0/src/Enzyme.jl:805 [inlined]
 [2] gradient(::AutoEnzyme{ReverseMode{false, FFIABI}}, f::Function, x::LinRange{Float64, Int64}, extras::Nothing)
   @ DifferentiationInterfaceEnzymeExt ~/.julia/packages/DifferentiationInterface/SOj30/ext/DifferentiationInterfaceEnzymeExt/reverse_allocating.jl:97
 [3] gradient(backend::AutoEnzyme{ReverseMode{false, FFIABI}}, f::Function, x::LinRange{Float64, Int64})
   @ DifferentiationInterface ~/.julia/packages/DifferentiationInterface/SOj30/src/gradient.jl:80
 [4] top-level scope
   @ REPL[60]:1

julia> Enzyme.autodiff(Enzyme.Reverse, f, Active(LinRange(1,2,3)))[1][1]
LinRange{Float64}(3.5, 5.5, 0)

julia> norm(ans)
0.0
```

**Comment by gdalle** [comment]
I don't think we can manage a general rule for stripping structure from arrays, so calling `similar` everywhere and dealing with the consequences seems more appropriate. For instance this has the benefit of preserving the sparsity pattern, whereas `similar(sparse_matrix, axes(sparse_matrix))` erases it.
Closing for now, maybe we can open more specific issues if it comes up
