### ISSUE TITLE
GitHub actions cost

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#390]
The CI workflows for DifferentiationInterface are getting bigger and bigger, due to the need to test with a lot of upstream and downstream dependencies.
Since we parallelize the tests to avoid compatibility conflicts, we are soon going to have:

- 3 Julia versions (`lts`, `1` and `pre`)
- 13 backends + second-order + a couple of integration tests (Lux, Flux)

That puts us around 50 workflows for every run, which is over the limit for the number of concurrent jobs (https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits). A GitHub Team or Enterprise plan would already make things faster.

In addition, some workflows might require Nvidia GPUs, which are not available with standard GitHub runners (except maybe in private beta, see https://github.blog/changelog/2023-10-31-run-your-ml-workloads-on-github-actions-with-gpu-runners/).

@ChrisRackauckas if DI becomes central in the ecosystem, do you think we could get funding for a GitHub subscription / custom GPU runners?

**Comment by ChrisRackauckas** [comment]
What funding source do you have in mind? We could in theory do a https://new.nsf.gov/funding/opportunities/pathways-enable-open-source-ecosystems-pose for JuliaDiff

**Comment by ChrisRackauckas** [comment]
Note that we do have on premise buildkite runners for GPUs hosted at MIT. It also has two exclusive nodes for huge jobs (benchmarks) and one set used for multithreaded runs / more CI. But we're a bit overloaded since PkgEval took a few of my nodes, so I need to find some more funding to build another machine (or kick PkgEval off my machines).

**Comment by gdalle** [comment]
@jpsamaroo let's talk next week about JuliaGPU buildkit

**Comment by ChrisRackauckas** [comment]
If you add to JuliaDiff it should just work.

**Comment by gdalle** [comment]
I know but Julian had offered to help debug the inevitable issues that will arise with the very first GPU tests, I'm not optimistic enough to think it will just work out of the box ^^

**Comment by gdalle** [comment]
DI is now part of JuliaDiff and we've just set up the buildkite pipeline (#617). All that's left is to figure out what to run on it
