### ISSUE TITLE
Adapt to pending Enzyme breaking change

### ISSUE THREAD

**Issue by wsmoses** [JuliaDiff/DifferentiationInterface.jl#468]
EnzymeRules for forward mode are defined differently [not relevant here]
ForwardMode moved DupNoNeed / Dup to specify if the return is needed or not -> Forward and ForwardWithPrimal

Runtime Activity is now in the mode

gradient/jacobian all optionall return values with the WithPrimal arg

**Comment by gdalle** [comment]
See also:

- https://github.com/EnzymeAD/Enzyme.jl/issues/1861
- https://github.com/SciML/ADTypes.jl/issues/85
