### ISSUE TITLE
Implement and test `gradient_and_hvp`

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#562]
It's the only missing piece for every operator to have a "value and" equivalent

**Comment by adrhill** [comment]
Unless you consider `value_gradient_and_hvp`.

**Comment by gdalle** [comment]
I'm not sure that this version is actually useful. My reasoning is that if you're computing HVPs, you might be trying to invert a Hessian linear system, in which case you're gonna do it many times and you don't care so much about the function value.

On the other hand, computing the gradient and the HVP together can be very beneficial, as shown in https://iclr-blogposts.github.io/2024/blog/bench-hvp/
