### ISSUE TITLE
Document what to do when differentiation fails

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#59]
Add a page to the docs explaining what to do when differentiation fails:

- ForwardDiff: type genericity, define dual overload
- ReverseDiff: type genericity
- Zygote, ChainRules: no mutation, custom rule
- FastDifferentiation: ?
- Enzyme: type stability

**Comment by adrhill** [comment]
The Julia AD ecosystem definitely needs such an overview somewhere, but I'm not sure DI is the right place, since we're generally trying to abstract backend implementation details away from users. 
Maybe this should live in [juliadiff.org](https://juliadiff.org)?

**Comment by adrhill** [comment]
On the other hand, this would be very user-friendly if combined with #57.

**Comment by gdalle** [comment]
yeah that was my thought, as part of your dream
