### ISSUE TITLE
Add `RegisterAction`

### ISSUE THREAD

**Issue by prbzrg** [JuliaDiff/DifferentiationInterface.jl#62]
It helps to create and register new releases.

https://github.com/julia-actions/RegisterAction

**Comment by gdalle** [comment]
Thanks, we are aware of this option but it is still unclear what the optimal design is, or whether we want to transfer the package to the JuliaDiff organization / merge it with AbstractDifferentiation. If we do decide to release, we'll definitely use that action!

**Comment by adrhill** [comment]
Is this action even required when using the [Julia Registrator](https://github.com/JuliaRegistries/Registrator.jl#install-registrator)? I've never had to use this action before.

**Comment by prbzrg** [comment]
The action is like an interface for `Registrator`. It facilitates version increasing and prompting `Registrator` before registration.

**Comment by adrhill** [comment]
Using Registrator, I already just have to comment `@ JuliaRegistrator register` on a commit to register a new version. What does this action add?

**Comment by prbzrg** [comment]
It gives you an interface in Github Action page that gets "major", "minor", or "patch" as the version input (or the literal version)
![Screenshot 2024-03-18 220013](https://github.com/gdalle/DifferentiationInterface.jl/assets/79970151/39384f04-e4d9-4d0e-bbfa-da646ae3233b)

then creates a new bump version commit with `@ JuliaRegistrator register`
![Screenshot 2024-03-18 220343](https://github.com/gdalle/DifferentiationInterface.jl/assets/79970151/3ac25981-e52d-4201-8bad-685a63ad5d7f)

**Comment by adrhill** [comment]
Thanks, TIL!

**Comment by gdalle** [comment]
me too!

**Comment by prbzrg** [comment]
now DI is having its second release. are you still considering this?

**Comment by prbzrg** [comment]
And having `TagBot` also helps.

https://github.com/JuliaRegistries/TagBot

**Comment by gdalle** [comment]
RegistrationAction can indeed help, but TagBot is apparently broken for packages located in subdirectories.
