### ISSUE TITLE
Allow `benchmark_differentiation` to (also) record the mean time

### ISSUE THREAD

**Issue by nsiccha** [JuliaDiff/DifferentiationInterface.jl#622]
Currently (I think) DifferentiationInterfaceTest.benchmark_differentiation only records the **minimum** benchmark runtime (see https://github.com/JuliaDiff/DifferentiationInterface.jl/blob/1e012dc1b4774c43ad96685c448855c802516132/DifferentiationInterfaceTest/src/tests/benchmark.jl#L104), but it would also be nice to be able to choose the **mean** benchmark runtime.

**Comment by gdalle** [comment]
That's a good idea! I think the best way is to add a keyword argument like "benchmark_aggregation" which defaults to the min function, and use it when aggregating samples.

**Comment by gdalle** [comment]
@nsiccha I think #639 gives you the flexibility you need

**Comment by nsiccha** [comment]
Cool!
