### ISSUE TITLE
Support for sparsity

### ISSUE THREAD

**Issue by prbzrg** [JuliaDiff/DifferentiationInterface.jl#63]
[`SparseDiffTools` ](https://github.com/JuliaDiff/SparseDiffTools.jl) has an interface to use different ADs. It would be good to have a benchmark against it. (or maybe replace current implementation with `DifferentiationInterface`)
It's interface:
`VecJac(f, v; autodiff = autodiff_backend) * x`
`JacVec(f, v; autodiff = autodiff_backend) * x`

**Comment by adrhill** [comment]
It only makes sense to compare identical backends, so the first step would be to support the sparse AD backends defined in [ADTypes.jl](https://sciml.github.io/ADTypes.jl/stable/).

**Comment by adrhill** [comment]
Or do these sparse backends make use of SparseDiffTools @gdalle?

**Comment by avik-pal** [comment]
The `sparse_jacobian` backend switches with sparse and non-sparse variants based on the sparsity detection algorithm

**Comment by avik-pal** [comment]
Also I wouldn't bother too much about the operators in SparseDiffTools, I have been meaning to rewrite them for quite some time. If you want to benchmark, https://github.com/SciML/NonlinearSolve.jl/blob/master/src/internal/operators.jl is a much better operator based implementation that will (hopefully) one day replace the sparsedifftools ones.

**Comment by gdalle** [comment]
Yeah @adrhill, the idea is that `AutoSparseSomething` in ADTypes.jl adds a SparseDiffTools.jl touch to the underlying backend `AutoSomething`. Basically those backend types were added _for_ SparseDiffTools.jl.

@prbzrg I plan to add support for sparsity (#7) but the preparation phase is a bit tricky so I haven't gotten around to it yet. Basically we would need to provide a config object + a cache object + a coloring, if I understand correctly. I'll look into that

**Comment by gdalle** [comment]
@avik-pal what's wrong with the SparseDiffTools operators?

**Comment by avik-pal** [comment]
FunctionOperator has been kind of broken in SciMLOperators (in terms of type stability and interface) for quite some time now. VecJac and JacVec construct that internally. In the long term, we want to fix function operator, but currently, there is a void regarding who wants to pick that up. The nonlinearsolve JacobianOperator essentially implements a type-stable interface for what FunctionOperator should looks like (but it misses some of the necessary functionality to make it general beyond jacobians)

**Comment by avik-pal** [comment]
Re interfacce issues: See https://github.com/SciML/SciMLOperators.jl/issues/223

**Comment by gdalle** [comment]
Once #135 is merged, sparse Jacobians and Hessians will be supported, with the precomputation of the sparsity pattern happening in the preparation step.
Since the low-level interface of SparseDiffTools is very messy and backend-specific, I only used the high-level one, implementing the Hessian as the Jacobian of the gradient.

**Comment by gdalle** [comment]
Update: the upcoming v1.0 of [ADTypes.jl](https://github.com/SciML/ADTypes.jl) will allow us to decouple

- sparsity pattern detection
- coloring algorithms
- batched jacobian/hessian column/row evaluations

Related:

- https://github.com/SciML/ADTypes.jl/issues/38

**Comment by gdalle** [comment]
As of right now, the main branch supports row-wise and column-wise estimation of sparse Jacobians, and column-wise estimation of sparse Hessians, using what is basically a clean reimplementation of SparseDiffTools. Closing this issue, feel free to reopen more specific ones
