### ISSUE TITLE
ForwardDiff Tag from `prepare_jacobian` not being applied to function in `jacobian!`

### ISSUE THREAD

**Issue by jClugstor** [JuliaDiff/DifferentiationInterface.jl#630]
I'm hitting this error related to the ForwardDiff tags:

```julia
ERROR: Invalid Tag object:
  Expected ForwardDiff.Tag{SciMLBase.UJacobianWrapper{true, ODEFunction{true, SciMLBase.AutoSpecialize, FunctionWrappersWrappers.FunctionWrappersWrapper{Tuple{FunctionWrappers.FunctionWrapper{Nothing, Tuple{Vector{Float64}, Vector{Float64}, SciMLBase.NullParameters, Float64}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, SciMLBase.NullParameters, Float64}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Vector{Float64}, SciMLBase.NullParameters, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Vector{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, SciMLBase.NullParameters, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}}, false}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Float64, SciMLBase.NullParameters}, Float64},
  Observed ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}.
```

`prepare_jacobian` was supplied with an ADType `ADTypes.AutoForwardDiff(chunksize=1, tag=ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}())`

but when using `DI.jacobian!` with the jacobian config, it looks like the function isn't using the provided tag. 

I'll try to make an MWE.

**Comment by gdalle** [comment]
An MWE would be really helpful. You may also want to read the discussion in #594

**Comment by jClugstor** [comment]
Actually, I think I might be trying to do something that doesn't make sense, at least with the ForwardDiff tag checking turned on. Is there a way to turn off the tag checking through DI?

**Comment by gdalle** [comment]
What would be your good reason to turn off tag checking? Usually it's a bad idea ^^
And no at the moment it is not possible to turn off tag checking from within DI, because the backend object has no such setting.

**Comment by jClugstor** [comment]
It has to do with the way function wrappers or function wrappers wrappers work, in ODE we need the tags of the user functions to all be the same. @oscardssmith would be able to explain it better. 

Ah right, the AutoForwardDiff ADType doesn't have such a setting. Hmm

**Comment by gdalle** [comment]
Specifying a custom tag inside the AutoForwardDiff backend is essentially equivalent to turning off tag checking though. So you could use tag=nothing and see what happens

**Comment by jClugstor** [comment]
It would still hit this line though `CHK && checktag(T, f, x)` right? We want to be able to not go through `checktag` at all.

**Comment by oscardssmith** [comment]
@gdalle the problem is that we are specifying a custom tag, but the tag checking is hitting.

**Comment by gdalle** [comment]
To bypass tag checking we would probably need to add a new type parameter like `AutoForwardDiff{chunksize,T,tagcheck}` in ADTypes, and then take it into account inside DI.

Will you also have a problem with tag precedence, i.e. the function below?

https://github.com/JuliaDiff/ForwardDiff.jl/blob/3acc8a64088564deec85103ed2dcc7cf6c0c2406/src/config.jl#L24-L26

**Comment by gdalle** [comment]
Alternatively, we could make it so that the default `tag = nothing` disables tag checking. If you don't want tag checking, you shouldn't need the custom tag at all, right?

**Comment by oscardssmith** [comment]
we very much do need the custom tag because the reason we are giving a custom tag is that we create a `FunctionWrapper` to prevent over-compiling on the integrated function, so we will get a MethodError unless the tag is `ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}`

**Comment by oscardssmith** [comment]
See https://www.stochasticlifestyle.com/improved-forwarddiff-jl-stacktraces-with-package-tags/ for a good description of our approach here.

**Comment by oscardssmith** [comment]
what we want isn't for the tag checking to be turned off, but for DI to generate duals with the tag that the jacobian cache prepared.

**Comment by gdalle** [comment]
Then please give me an MWE where it doesn't and I'll tell you whether that's a mistake on my end or not ^^ it's kind of hard to fix in a vacuum

**Comment by jClugstor** [comment]
Finally, I was able to get a MWE that shows what I'm talking about.
```julia
using OrdinaryDiffEqCore
using OrdinaryDiffEqSDIRK
using ADTypes
using ForwardDiff
using DiffEqBase
import DifferentiationInterface as DI

function lorenz!(du, u, p, t)
    du[1] = 10.0 * (u[2] - u[1])
    du[2] = u[1] * (28.0 - u[3]) - u[2]
    du[3] = u[1] * u[2] - (8 / 3) * u[3]
end

u0 = [1.0; 0.0; 0.0]
tspan = (0.0, 100.0)
prob = ODEProblem(lorenz!, u0, tspan)

integrator = DiffEqBase.__init(prob, ImplicitEuler())
OrdinaryDiffEqCore.@unpack nlsolver = integrator.cache
OrdinaryDiffEqCore.@unpack cache = nlsolver
OrdinaryDiffEqCore.@unpack du1, uf, jac_config = cache
J = [6.57121223582643e-310 0.0 6.5712076203142e-310; 0.0 6.5712076203142e-310 0.0; 6.57121342505034e-310 0.0 6.5712041387988e-310]

autodiff = AutoForwardDiff(chunksize = 1, tag = ForwardDiff.Tag(DiffEqBase.OrdinaryDiffEqTag(), eltype(integrator.u)))
jac_config = DI.prepare_jacobian(uf,du1,autodiff, integrator.u)

DI.jacobian!(uf, du1, J, jac_config, autodiff, integrator.u)
```
stacktrace 
```julia
ERROR: Invalid Tag object:
  Expected ForwardDiff.Tag{SciMLBase.UJacobianWrapper{true, ODEFunction{true, SciMLBase.AutoSpecialize, typeof(lorenz!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, Nothing, Nothing}, Float64, SciMLBase.NullParameters}, Float64},
  Observed ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}.
Stacktrace:
 [1] checktag(::Type{…}, f::SciMLBase.UJacobianWrapper{…}, x::Vector{…})
   @ ForwardDiff ~/.julia/packages/ForwardDiff/UBbGT/src/config.jl:34
 [2] jacobian!(result::Matrix{…}, f!::SciMLBase.UJacobianWrapper{…}, y::Vector{…}, x::Vector{…}, cfg::ForwardDiff.JacobianConfig{…}, ::Val{…})
   @ ForwardDiff ~/.julia/packages/ForwardDiff/UBbGT/src/jacobian.jl:80
 [3] jacobian!(result::Matrix{…}, f!::SciMLBase.UJacobianWrapper{…}, y::Vector{…}, x::Vector{…}, cfg::ForwardDiff.JacobianConfig{…})
   @ ForwardDiff ~/.julia/packages/ForwardDiff/UBbGT/src/jacobian.jl:79
 [4] jacobian!(::SciMLBase.UJacobianWrapper{…}, ::Vector{…}, ::Matrix{…}, ::DifferentiationInterfaceForwardDiffExt.ForwardDiffTwoArgJacobianPrep{…}, ::AutoForwardDiff{…}, ::Vector{…})
   @ DifferentiationInterfaceForwardDiffExt ~/.julia/packages/DifferentiationInterface/bulUW/ext/DifferentiationInterfaceForwardDiffExt/twoarg.jl:359
 [5] top-level scope
   @ ~/Documents/Work/dev/ODETesting/ODETest.jl:143
Some type information was truncated. Use `show(err)` to see complete types.
```
I'm pretty sure as long as checktag is on, this will always fail. The checktag function just checks if the tag used is the function type, and errors if it's not. This doesn't even get to the point of calculating the Jacobian because of checktag.

**Comment by gdalle** [comment]
Okay thanks, indeed that is an error in my code. I think that whenever a custom tag is passed, tag checking should be disabled in ForwardDiff.
I was testing custom tags with objects that were not created from `ForwardDiff.Tag`, and in that case `checktag` [always passes](https://github.com/JuliaDiff/ForwardDiff.jl/blob/3acc8a64088564deec85103ed2dcc7cf6c0c2406/src/config.jl#L42-L43) so I didn't see the error.

**Comment by gdalle** [comment]
The latest release v0.6.23 should fix this, thanks for reporting it!

**Comment by jClugstor** [comment]
In the versions of the operators that use a prep, maybe the tag type check should use the tag from the prep, since that's the one that's actually used in the operation?
e.g.
```julia
function DI.jacobian!(
    f!::F,
    y,
    jac,
    prep::ForwardDiffTwoArgJacobianPrep,
    backend::AutoForwardDiff,
    x,
    contexts::Vararg{Constant,C},
) where {F,C}
    fc! = with_contexts(f!, contexts...)
    CHK = tag_type(backend) === Nothing
    return jacobian!(jac, fc!, y, x, prep.config, Val(CHK))
end
```
if the tag in `backend` is nothing, but the tag in the prep is something, the tag check triggers.

**Comment by gdalle** [comment]
> if the tag in backend is nothing, but the tag in the prep is something, the tag check triggers.

That's on purpose. If the tag in the backend is `nothing` (the default), then we create a tag based on the function and its argument, as ForwardDiff normally would. Then tag-checking should proceed, and succeed.
