### ISSUE TITLE
Use traits instead of manual dispatch?

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#66]
The most widely used package is SimpleTraits.jl. However

- It doesn't do [dispatch on more than 1 trait](https://github.com/mauro3/SimpleTraits.jl?tab=readme-ov-file#details-of-method-dispatch), so we are not allowed to have `IsForward` and `IsReverse`
- For default arguments, the [value needs to be the same](https://github.com/mauro3/SimpleTraits.jl?tab=readme-ov-file#vararg-default-argument-and-keyword-argument-trait-functions) between trait and opposite trait, which means extra construction would be the same for `IsForward` and `!IsForward`

**Comment by adrhill** [comment]
Do we plan on adding more symbolic differentiation backends in the future? 
These would break the existing binary distinction between forward- and reverse-mode.

**Comment by gdalle** [comment]
I think we may want to add Symbolics.jl but unsure

Basically for symbolic ones we demand both pushforward and pullback. Note that in certain cases, Enzyme may also break the distinction (depending on how we define the mode).

**Comment by gdalle** [comment]
Fixed by #83, which overcomes the binary distinction nearly everywhere
