### ISSUE TITLE
Backends to support

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/DifferentiationInterface.jl#7]
- [x] ChainRulesCore: forward, reverse
- [x] Diffractor
- [x] Enzyme: forward, reverse
- [x] FastDifferentiation
- [x] FiniteDiff
- [x] FiniteDifferences
- [x] ForwardDiff
- [ ] [MathOptSymbolicAD](https://github.com/odow/MathOptSymbolicAD.jl)?
- [x] PolyesterForwardDiff
- [x] ReverseDiff
- [x] SparseDiffTools
- [x] Symbolics
- [x] Tapir
- [ ] TaylorDiff
- [x] Tracker
- [x] Zygote

**Comment by avik-pal** [comment]
Add `Tracker`(?); even if it seems abandoned, it has been one of the most reliable ones on GPUs (maybe after Zygote). Also, we need it for https://github.com/LuxDL/Lux.jl/issues/544.

**Comment by gdalle** [comment]
Easy peasy, I'll add it

**Comment by prbzrg** [comment]
The big list:
https://juliadiff.org/#the_big_list

**Comment by gdalle** [comment]
who do you think wrote that list ;)

**Comment by gdalle** [comment]
The backends ticked here all have basic support, but for optimal performance check out #115

**Comment by gdalle** [comment]
We support everything but TaylorDiff, no clue if it's worth adding it. The only case it makes sense is probably second derivatives

**Comment by gdalle** [comment]
TaylorDiff is too experimental, so I'm closing this in favor of the last remaining one https://github.com/odow/MathOptSymbolicAD.jl/issues/30
