### ISSUE TITLE
Add common interface for pullback functions

### ISSUE THREAD

**Issue by adrhill** [JuliaDiff/DifferentiationInterface.jl#72]
Reverse-mode backends like [Zygote](https://fluxml.ai/Zygote.jl/dev/adjoints/#Pullbacks-1) and [Enzyme (?)](https://enzymead.github.io/Enzyme.jl/stable/api/#EnzymeCore.autodiff_deferred_thunk-Union{Tuple{RABI},%20Tuple{ModifiedBetweenT},%20Tuple{Width},%20Tuple{ReturnShadow},%20Tuple{ReturnPrimal},%20Tuple{A},%20Tuple{FA},%20Tuple{EnzymeCore.ReverseModeSplit{ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI},%20Type{FA},%20Type{A},%20Vararg{Any}}}%20where%20{FA%3C:Annotation,%20A%3C:Annotation,%20ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI%3C:EnzymeCore.ABI}) are able to return pullback *functions / closures* instead of just the return value of the pullback, which is currently returned by `value_and_pullback!`.

DI could offer a common interface `value_and_pullback_fn` (or a mutating `value_and_pullback!_fn`) for users in need of such closures.

**Comment by gdalle** [comment]
At first I thought we would be able to pull this off with the `prepare` mechanism, but now I see that `prepare` is specific for _different inputs_, whereas we reuse a pullback for the _same input_. So you have my go ahead ^^

**Comment by gdalle** [comment]
Here's what I spotted:

**Forward mode**

- [ ] Diffractor: the pushforward seems to be the fundamental object, used in the [AbstractDifferentiation primitive](https://github.com/JuliaDiff/Diffractor.jl/blob/0f74c78584b342237a4682cfd68022215ef41f85/src/AbstractDifferentiation.jl#L15-L20)

**Reverse mode**

- [ ] ChainRulesCore: pullback closure generated by [`frule_via_ad`](https://juliadiff.org/ChainRulesCore.jl/stable/rule_author/superpowers/ruleconfig.html)
- [ ] Enzyme.jl: tape generated by [`autodiff_thunk`](https://enzymead.github.io/Enzyme.jl/stable/api/#EnzymeCore.autodiff_thunk-Union{Tuple{RABI},%20Tuple{ModifiedBetweenT},%20Tuple{Width},%20Tuple{ReturnShadow},%20Tuple{ReturnPrimal},%20Tuple{A},%20Tuple{FA},%20Tuple{EnzymeCore.ReverseModeSplit{ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI},%20Type{FA},%20Type{A},%20Vararg{Any}}}%20where%20{FA%3C:Annotation,%20A%3C:Annotation,%20ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI%3C:EnzymeCore.ABI}) (see [Enzyme.jl#1335](https://github.com/EnzymeAD/Enzyme.jl/issues/1335))
- [ ] Tracker: pullback closure generated by `forward`, see [README](https://github.com/FluxML/Tracker.jl?tab=readme-ov-file#introduction) or source code e.g. [here](https://github.com/FluxML/Tracker.jl/blob/01bc050525039fa2c9782ccecadb65534a34e695/src/back.jl#L174-L178)
- [ ] Zygote: pullback closure generated by [`pullback`](https://fluxml.ai/Zygote.jl/stable/adjoints/#Pullbacks-1)
